# Generated by Django 6.1 on 2026-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='network',
        ),
        migrations.AddField(
            model_name='show',
            name='extra_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='networks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
