# Generated by Django 6.1 on 2026-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_season_episodes_synced_at_show_last_viewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
