# Generated by Django 6.1 on 2026-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_showevent_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
