# Generated by Django 6.1 on 2026-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='origin_country',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
