# Generated by Django 6.1 on 2026-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_show_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='stills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
