# Generated by Django 6.1 on 2026-09-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_show_stills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='stills',
        ),
    ]
